In [1]:
import sys
import platform
import pandas as pd
import numpy as np
print(f"Executable Python: {sys.executable}")
print(f"Python Version: {platform.python_version()}")

#To show multiple outputs and misc. changes
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # Show all results without print (last_expr)

Executable Python: C:\Users\maity\.conda\envs\aku_mldl\python.exe
Python Version: 3.9.6


In [2]:
a= np.array([1,2,3])
a
print(a)

array([1, 2, 3])

[1 2 3]


In [3]:
b= np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:

# get dimension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
# get shape
a.shape
b.shape

(3,)

(2, 3)

In [7]:
# get type
a.dtype
b.dtype

dtype('int32')

dtype('float64')

In [8]:
a.itemsize 
# get size

4

In [9]:
#total size
a.size * a.itemsize
a.nbytes

12

12

In [10]:
a=np.array([[1,2,3,4,5,6,7],[5,6,7,8,9,10,11]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 5  6  7  8  9 10 11]]


In [11]:
# get a specific element[r,c]
a[1,5]
a[1,-4]

10

8

In [12]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# get a specific column
a[:,3]

array([4, 8])

In [14]:
# getting a little more fancy[startindex:endindex:stepzie]
a[0,1:6:2]

array([2, 4, 6])

In [16]:
 a[1,5]=20
 a
 a[:,2] = [1,2]
 a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 5,  6,  7,  8,  9, 20, 11]])

array([[ 1,  2,  1,  4,  5,  6,  7],
       [ 5,  6,  2,  8,  9, 20, 11]])

In [19]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b
#

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [21]:
# get specific element(work outside in)
b[0,1,1]


4

In [22]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [23]:
# replace an element
b[:,1,:]= [[9,9],[8,8]]

In [24]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initializing different types of arrays

In [25]:
# all 0's Matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [27]:
np.zeros((2,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [29]:
# all 1's matrix
np.ones((4,2,2),dtype = 'int32')


array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [30]:
# Any other nummber
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [32]:
np.full_like(a,4)
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [39]:
# random decimal numbers
# np.random.rand(4,2,3) similar example different method
np.random.random_sample(a.shape)

array([[0.31545134, 0.91707882, 0.36169865, 0.40504302, 0.64829759,
        0.1075508 , 0.35704543],
       [0.31227713, 0.55861139, 0.04863386, 0.52191296, 0.27071472,
        0.47012805, 0.95900641]])

In [46]:
# random integer values
np.random.randint(-2,9,size=(3,3))

array([[ 8,  1,  6],
       [ 4,  4,  6],
       [ 2, -2,  1]])

In [50]:
# the identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
# repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [62]:
output = np.ones((5,5))
output
z = np.zeros((3,3))
z
z[1,1]=9
output[1:4,1:4] = z
print (output)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [66]:
# careful while copying arrays
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)

[1 2 3]
[100   2   3]


## Mathematics Probabilities 

In [67]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [68]:
a+2

array([3, 4, 5, 6])

In [69]:
a-2

array([-1,  0,  1,  2])

In [70]:
a*2

array([2, 4, 6, 8])

In [71]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [72]:
b=np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [73]:
a **2

array([ 1,  4,  9, 16], dtype=int32)

In [76]:
# take the sin
np.sin(a)
np.cos(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## Linear Algebra

In [77]:
 a=np.ones((2,3))
 a
 b=np.full((3,2),2)
 b

array([[1., 1., 1.],
       [1., 1., 1.]])

array([[2, 2],
       [2, 2],
       [2, 2]])

In [79]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [81]:
# find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [82]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.min(stats)
np.min(stats,axis = 0)

1

array([1, 2, 3])

In [88]:
np.max(stats,axis =1)
np.max(stats)

array([3, 6])

6

In [89]:
np.sum(stats)

21

## reorganizing arrays

In [94]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

#after = before.reshape((4,2))
after = before.reshape((2,2,2))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [95]:
# vertical stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2])


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [96]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [97]:
# Horizontal stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscelleneous

## Boolean Masking and Advanced Indexing

In [103]:
pwd

'g:\\My Drive\\ineuron_MLDL\\Other_Training\\2_Numpy'

In [109]:
filedata = np.genfromtxt(r'data_sample.txt',delimiter =',')
filedata =filedata.astype('int32')
print(filedata)

[[ 1  2  3  4  5  6  7  8  9 10]
 [ 4  5  6 74 23  3  8  4  7 43]
 [ 6 12 13 14 15 16  5  8  4 11]]


In [112]:
filedata[filedata > 25]

array([74, 43])

In [113]:
## you can index with a list in numpy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [121]:
np.any(filedata>15,axis = 0)

array([False, False, False,  True,  True,  True, False, False, False,
        True])

In [122]:
np.all(filedata>15,axis = 0)

array([False, False, False, False, False, False, False, False, False,
       False])

In [124]:
np.any(filedata>15,axis = 1)

array([False,  True,  True])

In [125]:
((filedata>15) & (filedata <100))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True,  True, False, False, False, False,
         True],
       [False, False, False, False, False,  True, False, False, False,
        False]])

In [126]:
(~((filedata>15) & (filedata <100)))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True, False, False,  True,  True,  True,  True,
        False],
       [ True,  True,  True,  True,  True, False,  True,  True,  True,
         True]])